final version

diff --git a/srcs/requirements/mariadb/tools/mariadb-hardering b/srcs/requirements/mariadb/tools/mariadb-hardering
--- a/srcs/requirements/mariadb/tools/mariadb-hardering
+++ b/srcs/requirements/mariadb/tools/mariadb-hardering
@@ -1,77 +1,46 @@
 #!/usr/bin/env sh
 
-MYSQL="/usr/bin/env mysqld --bootstrap"
-
-mysql()
-{
-	if [ $1 == 'sendall' ]
-	then
-		echo "${MYSQL_MESSAGE}" | ${MYSQL}
-		MYSQL_MESSAGE=
-	else
-		MYSQL_MESSAGE=${MYSQL_MESSAGE}$(mysql_"$@")
-	fi
-}
-
-mysql_createdb()
-{
-echo "
-CREATE DATABASE IF NOT EXISTS $1;
-"
-}
-
-mysql_dropdb()
-{
-echo "
-DROP DATABASE IF EXISTS $1;
-"
-}
-
-mysql_adduser()
-{
-echo "
-FLUSH PRIVILEGES;
-CREATE USER IF NOT EXISTS '$1'@'$2' IDENTIFIED BY '$3';
-"
-}
-
-mysql_moduser_pass()
-{
-echo "
-FLUSH PRIVILEGES;
-ALTER USER IF EXISTS '$1'@'$2' IDENTIFIED BY '$3';
-"
-}
-
-mysql_deluser()
-{
-echo "
-FLUSH PRIVILEGES;
-DROP USER IF EXISTS '$1'@'$2';
-"
-}
-
-mysql_grant()
-{
-echo "
-FLUSH PRIVILEGES;
-GRANT ALL PRIVILEGES ON $1.* TO '$2'@'$3';
-"
-}
-
 generate_root_pass()
 {
 	< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-16}
 }
 
-MYSQL_ROOT_PASS=$(generate_root_pass)
-echo "MYSQL root random key generated (you should save it): ${MYSQL_ROOT_PASS}"
-#mysql createdb ${WORDPRESS_DATABASE}
-mysql moduser_pass root localhost ${MYSQL_ROOT_PASS}
-mysql adduser ${WORDPRESS_USERNAME} ${WORDPRESS_USERHOST} ${WORDPRESS_USERPASS}
-mysql grant ${WORDPRESS_DATABASE} ${WORDPRESS_USERNAME} ${WORDPRESS_USERHOST}
-mysql deluser mysql localhost
-mysql deluser '' localhost
-mysql deluser '' mariadb
-mysql sendall
+if [ ! -d "${VOLUME_MOUNT_PATH}/mysql" ]; then
+	MYSQL_ROOT_PASS=$(generate_root_pass)
+	echo "MYSQL root random key generated (you should save it): ${MYSQL_ROOT_PASS}"
 
+	mysql_install_db > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "I can't initialize MySQL database. Exiting!!"
+		exit 1
+	fi
+
+	cat << EOF | mysqld --bootstrap
+USE mysql;
+FLUSH PRIVILEGES;
+
+DROP DATABASE IF EXISTS test;
+-- CREATE DATABASE IF NOT EXISTS ${WORDPRESS_DATABASE};
+
+ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASS}';
+CREATE USER IF NOT EXISTS '${WORDPRESS_USERNAME}'@'${WORDPRESS_USERHOST}' IDENTIFIED BY '${WORDPRESS_USERPASS}';
+GRANT ALL PRIVILEGES ON ${WORDPRESS_DATABASE}.* TO '${WORDPRESS_USERNAME}'@'${WORDPRESS_USERHOST}';
+
+DROP USER ''@${HOSTNAME};
+
+-- drop empty and mysql users
+-- SELECT GROUP_CONCAT('\'',user, '\'@\'', host, '\'') INTO @users FROM mysql.user WHERE user = 'mysql' OR user = '';
+-- SET @users = CONCAT('DROP USER ', @users);
+-- PREPARE stmt FROM @users;
+-- EXECUTE stmt;
+
+FLUSH PRIVILEGES;
+
+EOF
+
+	if [ $? -ne 0 ]; then
+		echo "I can't secure the MySQL permissions. Exiting!!"
+		exit 1
+	fi
+
+fi
